
import java.awt.BorderLayout;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author javiifu
 */
public class frmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipal.class.getName());

    /**
     * Creates new form Login
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_Fondo = new javax.swing.JPanel();
        jpn_Menu = new javax.swing.JPanel();
        btn_usuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_Empleado1 = new javax.swing.JButton();
        jpn_MenuV = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnContabilidad = new javax.swing.JButton();
        Contenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpn_Fondo.setBackground(new java.awt.Color(255, 255, 255));

        jpn_Menu.setBackground(new java.awt.Color(31, 87, 161));

        btn_usuario.setBackground(new java.awt.Color(255, 255, 255));
        btn_usuario.setForeground(new java.awt.Color(0, 0, 0));
        btn_usuario.setText("Usuario");
        btn_usuario.setBorder(null);
        btn_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuarioActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/javiifu/Descargas/LOGO-cesur.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(198, 168));
        jLabel2.setMinimumSize(new java.awt.Dimension(198, 168));
        jLabel2.setPreferredSize(new java.awt.Dimension(198, 168));

        btn_Empleado1.setBackground(new java.awt.Color(255, 255, 255));
        btn_Empleado1.setForeground(new java.awt.Color(0, 0, 0));
        btn_Empleado1.setText("Empleados");
        btn_Empleado1.setBorder(null);
        btn_Empleado1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Empleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Empleado1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpn_MenuLayout = new javax.swing.GroupLayout(jpn_Menu);
        jpn_Menu.setLayout(jpn_MenuLayout);
        jpn_MenuLayout.setHorizontalGroup(
            jpn_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Empleado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpn_MenuLayout.setVerticalGroup(
            jpn_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_MenuLayout.createSequentialGroup()
                .addGroup(jpn_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btn_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn_MenuLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(btn_Empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(352, Short.MAX_VALUE))
        );

        jpn_MenuV.setBackground(new java.awt.Color(245, 162, 92));
        jpn_MenuV.setLayout(null);

        btnClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnClientes.setText("Clientes");
        btnClientes.setBorder(null);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jpn_MenuV.add(btnClientes);
        btnClientes.setBounds(40, 40, 90, 30);

        btnPedidos.setBackground(new java.awt.Color(255, 255, 255));
        btnPedidos.setForeground(new java.awt.Color(0, 0, 0));
        btnPedidos.setText("Pedidos");
        btnPedidos.setBorder(null);
        btnPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        jpn_MenuV.add(btnPedidos);
        btnPedidos.setBounds(160, 40, 100, 30);

        btnContabilidad.setBackground(new java.awt.Color(255, 255, 255));
        btnContabilidad.setForeground(new java.awt.Color(0, 0, 0));
        btnContabilidad.setText("Productos");
        btnContabilidad.setBorder(null);
        btnContabilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContabilidadActionPerformed(evt);
            }
        });
        jpn_MenuV.add(btnContabilidad);
        btnContabilidad.setBounds(280, 40, 110, 30);

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setPreferredSize(new java.awt.Dimension(831, 535));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PANTALLA DE INICIO");

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpn_FondoLayout = new javax.swing.GroupLayout(jpn_Fondo);
        jpn_Fondo.setLayout(jpn_FondoLayout);
        jpn_FondoLayout.setHorizontalGroup(
            jpn_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_FondoLayout.createSequentialGroup()
                .addComponent(jpn_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpn_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpn_MenuV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jpn_FondoLayout.setVerticalGroup(
            jpn_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpn_MenuV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jpn_FondoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpn_Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuarioActionPerformed
        Inicio(1);
    }//GEN-LAST:event_btn_usuarioActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        Inicio(2);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        Inicio(3);
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnContabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContabilidadActionPerformed
        Inicio(4);
    }//GEN-LAST:event_btnContabilidadActionPerformed

    private void btn_Empleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Empleado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Empleado1ActionPerformed
/*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }*/
   
    
    private void Inicio(int opcion){
        jpnUsuario pl_user = new jpnUsuario();
        jpnClientes pl_cliente = new jpnClientes();
        jpnPedidos pl_pedidos = new jpnPedidos();
        jpnProductos pl_productos = new jpnProductos();
        jpnEmpleados pl_empleado = new jpnEmpleados();
        
        Contenido.removeAll();
        
        switch(opcion){
            
            case 1:
                pl_user.setSize(831,535);
                pl_user.setLocation(0, 0);
                Contenido.add(pl_user,BorderLayout.CENTER);
                Contenido.revalidate();
                Contenido.repaint();
                break;
            
            case 2:
                pl_cliente.setSize(831,535);
                pl_cliente.setLocation(0, 0);
                Contenido.add(pl_cliente,BorderLayout.CENTER);
                Contenido.revalidate();
                Contenido.repaint();
                break;
                
            case 3:
                pl_pedidos.setSize(750,430);
                pl_pedidos.setLocation(0, 0);
                Contenido.add(pl_pedidos,BorderLayout.CENTER);
                Contenido.revalidate();
                Contenido.repaint();
                break;
                
            case 4:
                pl_productos.setSize(750,430);
                pl_productos.setLocation(0, 0);
                Contenido.add(pl_productos, BorderLayout.CENTER);
                Contenido.revalidate();
                Contenido.repaint();
                break;
                
            case 5:
                pl_empleado.setSize(750,430);
                pl_empleado.setLocation(0, 0);
                Contenido.add(pl_empleado, BorderLayout.CENTER);
                Contenido.revalidate();
                Contenido.repaint();
                break;
                
            
             
            
        }   
        
    }
    /*
    private void mostrarClientes(){
        
        jpnClientes pl_cliente = new jpnClientes();
        pl_cliente.setSize(750,430);
        pl_cliente.setLocation(0,0);
        Contenido.removeAll();
        Contenido.add(pl_cliente, BorderLayout.CENTER);
        Contenido.revalidate(); //
        Contenido.repaint();
    }
    
    private void mostrarPedidos(){
       jpnPedidos pl_pedidos = new jpnPedidos();
       pl_pedidos.setSize(750,430);
       pl_pedidos.setLocation(0,0);
       Contenido.removeAll();
       Contenido.add(pl_pedidos, BorderLayout.CENTER);
       Contenido.revalidate(); //
       Contenido.repaint();
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnContabilidad;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btn_Empleado1;
    private javax.swing.JButton btn_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jpn_Fondo;
    private javax.swing.JPanel jpn_Menu;
    private javax.swing.JPanel jpn_MenuV;
    // End of variables declaration//GEN-END:variables
}
